"""create files table

Revision ID: 0e0d242438bc
Revises: 87ed1cbb1088
Create Date: 2025-05-21 00:43:40.462927

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e0d242438bc'
down_revision: Union[str, Sequence[str], None] = '87ed1cbb1088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('filename', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('filepath', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('key', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('extension', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('mime_type', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_files_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
