"""新增一个email字段

Revision ID: 2761d7b50203
Revises: cf06bc8829c1
Create Date: 2026-06-30 19:09:01.323359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2761d7b50203'
down_revision: Union[str, Sequence[str], None] = 'cf06bc8829c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'email')
    # ### end Alembic commands ###
