"""create sessions table

Revision ID: 87ed1cbb1088
Revises:
Create Date: 2025-05-14 10:23:53.200946

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ed1cbb1088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('sandbox_id', sa.String(length=255), nullable=True),
                    sa.Column('task_id', sa.String(length=255), nullable=True),
                    sa.Column('title', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('unread_message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('latest_message', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('latest_message_at', sa.DateTime(), nullable=True),
                    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('memories', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_sessions_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
