"""empty message

Revision ID: cf06bc8829c1
Revises: 747364b8505b
Create Date: 2026-06-30 18:48:42.450779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf06bc8829c1'
down_revision: Union[str, Sequence[str], None] = '747364b8505b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'avatar')
    # ### end Alembic commands ###
